version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - "rabbitmq_data:/data"
  
volumes:
  rabbitmq_data:

# docker run --name rabbitmq -p 15672:15672 rabbitmq:3-management 
# access the management ui on localhost:15672